### ISSUE TITLE
Broken link "Anomaly detection in industrial time series"

### ISSUE THREAD

**Issue by mallibus** [AndreaPi/Open-industrial-datasets#1]
Hi Andrea, the link at the caption "Anomaly detection in industrial time series" looks to be broken 
https://itrust.sutd.edu.sg/research/dataset/dataset_characteristics/#swat

**Comment by AndreaPi** [comment]
It's not exactly broken - it's just that it's private. You can only access it after compiling this [data request](https://itrust.sutd.edu.sg/itrust-labs_datasets/) (which arguably doesn't make the dataset very open!). I'll clarify this.
